### ISSUE TITLE
get_interfaces_ip()

### ISSUE THREAD

**Issue by jmrenshaw** [napalm-automation/napalm-cumulus#19]
I'll make a start on this one as it will mostly be based on the previous get_interfaces function.  Once I've got some working code I would like a bit of guidance on contributing to the testing code as well so that I can make sure this is working as well as the function itself.

**Comment by dbarrosop** [comment]
Happy to help, you can see some guidelines here:

https://napalm.readthedocs.io/en/latest/contributing/index.html#implementing-an-already-defined-method

**Comment by jmrenshaw** [comment]
I have added the code for get_interface_ip and some mock data.  Could someone have a look at the test data as I haven't used this before. https://github.com/jmrenshaw/napalm-cumulus/tree/Issue%2319
If it looks good then I will issue a pull request.  @dbarrosop I would definitely be interested in looking at the YANG framework.

**Comment by dbarrosop** [comment]
Sorry for late response:

> Could someone have a look at the test data as I haven't used this before

Could you open a PR? It's easier.

> If it looks good then I will issue a pull request. @dbarrosop I would definitely be interested in looking at the YANG framework.

You can find all the info in the napalm-yang repo. I am still working on the framework but feel free to play a bit.

**Comment by jmrenshaw** [comment]
Closed with PR #20
